export const NOTIFICATION_TYPES = {
  LOGIN_ANOMALY: "LOGIN_ANOMALY",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  APP_AVAILABLE: "APP_AVAILABLE",
  ENTITLEMENT_GRANTED: "ENTITLEMENT_GRANTED",
  ENTITLEMENT_REVOKED: "ENTITLEMENT_REVOKED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT"
} as const;

export const NOTIFICATION_CONFIG = {
  TITLE_MAX_LENGTH: 200,
  MESSAGE_MAX_LENGTH: 2000
} as const;
