export const ERROR_CODES = {
  // ── Common HTTP ──
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // ── Infrastructure ──
  DATABASE_ERROR: "DATABASE_ERROR",
  REDIS_ERROR: "REDIS_ERROR",

  // ── Mongoose / MongoDB ──
  DUPLICATE_KEY: "DUPLICATE_KEY",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_OBJECT_ID: "INVALID_OBJECT_ID",

  // ── Auth Guard ──
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  AUTH_ADMIN_ONLY: "AUTH_ADMIN_ONLY",

  // ── JWT ──
  JWT_INVALID: "JWT_INVALID",
  JWT_EXPIRED: "JWT_EXPIRED",

  // ── Token ──
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",

  // ── Login ──
  LOGIN_ACCOUNT_LOCKED: "LOGIN_ACCOUNT_LOCKED",
  LOGIN_INVALID_EMAIL: "LOGIN_INVALID_EMAIL",
  LOGIN_ACCOUNT_INACTIVE: "LOGIN_ACCOUNT_INACTIVE",
  LOGIN_EMAIL_NOT_VERIFIED: "LOGIN_EMAIL_NOT_VERIFIED",
  LOGIN_INVALID_CREDENTIALS: "LOGIN_INVALID_CREDENTIALS",
  LOGIN_OTP_COOLDOWN: "LOGIN_OTP_COOLDOWN",
  LOGIN_OTP_RESEND_LIMIT: "LOGIN_OTP_RESEND_LIMIT",
  LOGIN_OTP_LOCKED: "LOGIN_OTP_LOCKED",
  LOGIN_OTP_INVALID: "LOGIN_OTP_INVALID",
  LOGIN_MAGIC_LINK_COOLDOWN: "LOGIN_MAGIC_LINK_COOLDOWN",
  LOGIN_MAGIC_LINK_INVALID: "LOGIN_MAGIC_LINK_INVALID",
  LOGIN_USER_NOT_FOUND: "LOGIN_USER_NOT_FOUND",

  // ── Signup ──
  SIGNUP_EMAIL_EXISTS: "SIGNUP_EMAIL_EXISTS",
  SIGNUP_OTP_COOLDOWN: "SIGNUP_OTP_COOLDOWN",
  SIGNUP_OTP_LOCKED: "SIGNUP_OTP_LOCKED",
  SIGNUP_OTP_INVALID: "SIGNUP_OTP_INVALID",
  SIGNUP_RESEND_LIMIT: "SIGNUP_RESEND_LIMIT",
  SIGNUP_SESSION_INVALID: "SIGNUP_SESSION_INVALID",

  // ── Forgot Password ──
  FORGOT_PASSWORD_OTP_COOLDOWN: "FORGOT_PASSWORD_OTP_COOLDOWN",
  FORGOT_PASSWORD_OTP_RESEND_LIMIT: "FORGOT_PASSWORD_OTP_RESEND_LIMIT",
  FORGOT_PASSWORD_AUTH_NOT_FOUND: "FORGOT_PASSWORD_AUTH_NOT_FOUND",
  FORGOT_PASSWORD_OTP_LOCKED: "FORGOT_PASSWORD_OTP_LOCKED",
  FORGOT_PASSWORD_OTP_INVALID: "FORGOT_PASSWORD_OTP_INVALID",
  FORGOT_PASSWORD_MAGIC_LINK_COOLDOWN: "FORGOT_PASSWORD_MAGIC_LINK_COOLDOWN",
  FORGOT_PASSWORD_MAGIC_LINK_RESEND_LIMIT:
    "FORGOT_PASSWORD_MAGIC_LINK_RESEND_LIMIT",
  FORGOT_PASSWORD_MAGIC_LINK_INVALID: "FORGOT_PASSWORD_MAGIC_LINK_INVALID",
  FORGOT_PASSWORD_INVALID_RESET_TOKEN: "FORGOT_PASSWORD_INVALID_RESET_TOKEN",

  // ── Change Password ──
  CHANGE_PASSWORD_WRONG_CURRENT: "CHANGE_PASSWORD_WRONG_CURRENT",
  CHANGE_PASSWORD_SAME_AS_CURRENT: "CHANGE_PASSWORD_SAME_AS_CURRENT",

  // ── Unlock Account ──
  UNLOCK_COOLDOWN: "UNLOCK_COOLDOWN",
  UNLOCK_RATE_LIMIT: "UNLOCK_RATE_LIMIT",
  UNLOCK_ACCOUNT_DISABLED: "UNLOCK_ACCOUNT_DISABLED",
  UNLOCK_ACCOUNT_NOT_LOCKED: "UNLOCK_ACCOUNT_NOT_LOCKED",
  UNLOCK_AUTH_NOT_FOUND: "UNLOCK_AUTH_NOT_FOUND",
  UNLOCK_INVALID_TEMP_PASSWORD: "UNLOCK_INVALID_TEMP_PASSWORD",
  UNLOCK_TEMP_PASSWORD_EXPIRED: "UNLOCK_TEMP_PASSWORD_EXPIRED",
  UNLOCK_USER_NOT_FOUND: "UNLOCK_USER_NOT_FOUND",

  // ── User ──
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ADMIN_CANNOT_LOCK_SELF: "ADMIN_CANNOT_LOCK_SELF",
  ADMIN_CANNOT_LOCK_LAST_ADMIN: "ADMIN_CANNOT_LOCK_LAST_ADMIN",
  ADMIN_CANNOT_RESET_SELF: "ADMIN_CANNOT_RESET_SELF",

  // ── Contact Admin ──
  CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",

  // ── Login History ──
  LOGIN_HISTORY_NOT_FOUND: "LOGIN_HISTORY_NOT_FOUND",

  // ── Web App ──
  WEB_APP_NAME_EXISTS: "WEB_APP_NAME_EXISTS",
  WEB_APP_CATEGORY_NOT_FOUND: "WEB_APP_CATEGORY_NOT_FOUND",
  WEB_APP_NOT_FOUND: "WEB_APP_NOT_FOUND",

  // ── Favorite ──
  FAVORITE_APP_NOT_FOUND: "FAVORITE_APP_NOT_FOUND",

  // ── Notification ──
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // ── Validation ──
  VALIDATION_EMAIL_REQUIRED: "VALIDATION_EMAIL_REQUIRED",
  VALIDATION_EMAIL_INVALID: "VALIDATION_EMAIL_INVALID",
  VALIDATION_OBJECT_ID_REQUIRED: "VALIDATION_OBJECT_ID_REQUIRED",
  VALIDATION_OBJECT_ID_INVALID: "VALIDATION_OBJECT_ID_INVALID",
  VALIDATION_FIELD_REQUIRED: "VALIDATION_FIELD_REQUIRED",
  VALIDATION_FIELD_TOO_SHORT: "VALIDATION_FIELD_TOO_SHORT",
  VALIDATION_FIELD_TOO_LONG: "VALIDATION_FIELD_TOO_LONG"
} as const;
