export const FORGOT_PASSWORD_OTP_CONFIG = {
  LENGTH: 6,
  EXPIRY_MINUTES: 5,
  COOLDOWN_SECONDS: 60,
  MAX_FAILED_ATTEMPTS: 5,
  MAX_RESEND_ATTEMPTS: 3,
  LOCKOUT_DURATION_MINUTES: 15
} as const;

export const FORGOT_PASSWORD_MAGIC_LINK_CONFIG = {
  TOKEN_LENGTH: 64,
  EXPIRY_MINUTES: 15,
  COOLDOWN_SECONDS: 60,
  MAX_RESEND_ATTEMPTS: 3
} as const;

export const FORGOT_PASSWORD_RESET_TOKEN_CONFIG = {
  TOKEN_LENGTH: 64,
  EXPIRY_MINUTES: 10
} as const;
