const ERROR_CODES = {
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  CHANGE_PASSWORD_WRONG_CURRENT: "CHANGE_PASSWORD_WRONG_CURRENT",
  CHANGE_PASSWORD_SAME_AS_CURRENT: "CHANGE_PASSWORD_SAME_AS_CURRENT",
  WEB_APP_NAME_EXISTS: "WEB_APP_NAME_EXISTS",
  WEB_APP_CATEGORY_NOT_FOUND: "WEB_APP_CATEGORY_NOT_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_NAME_TAKEN: "CATEGORY_NAME_TAKEN",
  CATEGORY_REASSIGN_REQUIRED: "CATEGORY_REASSIGN_REQUIRED",
  CATEGORY_REASSIGN_INVALID: "CATEGORY_REASSIGN_INVALID",
  CATEGORY_IMPACT_CHANGED: "CATEGORY_IMPACT_CHANGED"
} as const;

export default ERROR_CODES;
